FROM clickhouse/clickhouse-server:latest

# Install cron, Python, and pip
RUN apt-get update && apt-get install -y cron python3 python3-pip curl

# Install Python modules
RUN pip3 install clickhouse_driver

# Add your scripts
COPY collect_sys /usr/local/bin/collect_sys
COPY pt-summary /usr/local/bin/pt-summary

# Give execute permission
RUN chmod +x /usr/local/bin/collect_sys /usr/local/bin/pt-summary

# Add cron job
RUN (crontab -l 2>/dev/null; echo "* * * * * /usr/bin/python3 /usr/local/bin/collect_sys >> /var/log/cron.log 2>&1") | crontab -

# Copy the entrypoint script into the container
COPY entrypoint.sh /usr/local/bin/

# Set the entrypoint script to be executed
ENTRYPOINT ["entrypoint.sh"]

