version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    container_name: zookeeper
    networks:
      my-network:
        ipv4_address: 172.20.0.5
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"
  clickhouse01:
    build:
      context: .
      dockerfile: Dockerfile-clickhouse
    hostname: clickhouse01
    container_name: clickhouse01
    ports:
      - 9001:9000
      - 8124:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.20.0.2
    extra_hosts:
      - "clickhouse02:172.20.0.3"
    depends_on:
      - zookeeper
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./clusters.xml:/etc/clickhouse-server/config.d/clusters.xml
      - ./listen_host.xml:/etc/clickhouse-server/config.d/listen_host.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./macros_1.xml:/etc/clickhouse-server/config.d/macros.xml  
  clickhouse02:
    build:
      context: .
      dockerfile: Dockerfile-clickhouse
    hostname: clickhouse02
    container_name: clickhouse02
    ports:
      - 9002:9000
      - 8125:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.20.0.3
    extra_hosts:
      - "clickhouse01:172.20.0.2"
    depends_on:
      - zookeeper
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./clusters.xml:/etc/clickhouse-server/config.d/clusters.xml
      - ./listen_host.xml:/etc/clickhouse-server/config.d/listen_host.xml
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./macros_1.xml:/etc/clickhouse-server/config.d/macros.xml  
networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
